// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6-AD9-kntzh-vTJM50_-QrgFi_5KnJ6Q',
    appId: '1:128039296525:web:1aa0929458e9eedece7f44',
    messagingSenderId: '128039296525',
    projectId: 'final-project-84ca0',
    authDomain: 'final-project-84ca0.firebaseapp.com',
    storageBucket: 'final-project-84ca0.appspot.com',
    measurementId: 'G-Y3ZHDMM8MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9oQTzUIijeL_qQtIqbEb7m8BsJDRJoKw',
    appId: '1:128039296525:android:49c824afeaaf69b1ce7f44',
    messagingSenderId: '128039296525',
    projectId: 'final-project-84ca0',
    storageBucket: 'final-project-84ca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUP9BDuUKr3Ljhi8inul1hEaysPHNIrJI',
    appId: '1:128039296525:ios:dbb4a6a7459658a4ce7f44',
    messagingSenderId: '128039296525',
    projectId: 'final-project-84ca0',
    storageBucket: 'final-project-84ca0.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUP9BDuUKr3Ljhi8inul1hEaysPHNIrJI',
    appId: '1:128039296525:ios:dbb4a6a7459658a4ce7f44',
    messagingSenderId: '128039296525',
    projectId: 'final-project-84ca0',
    storageBucket: 'final-project-84ca0.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6-AD9-kntzh-vTJM50_-QrgFi_5KnJ6Q',
    appId: '1:128039296525:web:ddbdd9aca804fce8ce7f44',
    messagingSenderId: '128039296525',
    projectId: 'final-project-84ca0',
    authDomain: 'final-project-84ca0.firebaseapp.com',
    storageBucket: 'final-project-84ca0.appspot.com',
    measurementId: 'G-M8B6CLEPYH',
  );
}
